### ISSUE TITLE
Minor logic tweaks

### ISSUE THREAD

**Issue by krebeDev** [jonahunuafe/e-commerce-product-page#1]
@jonahunuafe this looks great!

Here are a few improvements you should make:

1. After adding items to the cart, subsequent clicks on the "plus" or "minus" buttons should directly update the number of items in the cart (the count on top of the cart and the count inside the popup should be updated).
2. Deleting the cart item(s) should also reset the items count (label between the "plus" and "minus") to zero
3. When the cart popup opens, clicking anywhere outside of it should close it.

**Comment by jonahunuafe** [comment]
Point 2 and 3 have been fully implemented. For point 1, subsequent clicks on the plus and minus button directly updates the number of items in the cart (the count on top of the cart and the count inside the popup) as suggested improvements. But u need to click on the add to cart button before it can calculate the total amount of items bought, which I think might confuse the user. I think forgoing point 1 will be better to avoid been caught in the web.
